file mkdir build 
cd build
source ../xsa_scripts/project.tcl
source ../xsa_scripts/dr.bd.tcl
source ../xsa_scripts/pfm_decls.tcl

set pre_synth ""

if { $argc > 1} {
  set pre_synth [lindex $argv 2]
}
if {$pre_synth} {
  set_property platform.platform_state "pre_synth" [current_project]

  write_hw_platform -force $PLATFORM_NAME.xsa
  validate_hw_platform $PLATFORM_NAME.xsa -verbose 
} else {
  set_property generate_synth_checkpoint true [get_files -norecurse *.bd]
  launch_runs impl_1 -to_step write_bitstream -jobs 16
  wait_on_run impl_1
  #set_property platform.post_sys_link_tcl_hook ./dynamic_postlink.tcl [current_project]
  write_hw_platform -include_bit $PLATFORM_NAME.xsa

  validate_hw_platform $PLATFORM_NAME.xsa
}
#write README.hw
set board zcu104

set fd [open README.hw w] 

set board [lindex $argv 0]

puts $fd "##########################################################################"
puts $fd "This is a brief document containing design specific details for : ${board}"
puts $fd "This is auto-generated by Petalinux ref-design builder created @ [clock format [clock seconds] -format {%a %b %d %H:%M:%S %Z %Y}]"
puts $fd "##########################################################################"

set board_part [get_board_parts [current_board_part -quiet]]
if { $board_part != ""} {
  puts $fd "BOARD: $board_part" 
}

set design_name [get_property NAME [get_bd_designs]]
puts $fd "BLOCK DESIGN: $design_name" 

set columns {%40s%30s%15s%50s}
puts $fd [string repeat - 150]
puts $fd [format $columns "MODULE INSTANCE NAME" "IP TYPE" "IP VERSION" "IP"]
puts $fd [string repeat - 150]
foreach ip [get_ips] {
  set catlg_ip [get_ipdefs -all [get_property IPDEF $ip]] 
  puts $fd [format $columns [get_property NAME $ip] [get_property NAME $catlg_ip] [get_property VERSION $catlg_ip] [get_property VLNV $catlg_ip]]
}
close $fd

cd ..
